### ISSUE TITLE
RongtaPrinterSDK missing

### ISSUE THREAD

**Issue by aldoggr** [Cacata/Printing.With.Xamarin.iOS#1]
Hi!
I've downloaded your repo to test it, and found that the RongtaPrinterSDK is missing. Where can I download it?

**Comment by ZeMidF10** [comment]
+1

**Comment by Cacata** [comment]
Hey guys,

This library is private with company copyright. This is why I didn't add into the project. But I did it getting the supplier library and creating a DLL from Objective-C to Swift. After this you must to converting to dll the Swift library to put it into xamarin project.

Take in consideration make 2 different libraries. One for images formats and then other one to manipulate the printer. **All this code is provide in Objective-C**.

The way used to convert this code was: https://docs.microsoft.com/en-us/xamarin/ios/platform/binding-objective-c/

Greetings.
